# Generated by Django 3.2.9 on 2021-11-29 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='christmasletter',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='christmasletter',
            name='items',
        ),
        migrations.AddField(
            model_name='christmasletter',
            name='items',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
