# Generated by Django 3.2.9 on 2021-11-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_auto_20211129_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='christmasletter',
            name='items',
        ),
    ]
